[package]
authors = ["itang <live.tang@gmail.com>"]
name = "deftype-server-rs"
version = "0.1.0"

[dependencies]
ansi_term = "0.7.1"
chrono = "0.2.19"
clippy = "0.0.37"
diesel = "0.5.0"
dotenv = "0.8.0"
dotenv_macros = "0.8.0"
hyper = "0.7.2"
iron = "0.2.6"
lazy_static = "0.1.15"
mount = "0.0.9"
r2d2 = "0.6.3"
r2d2-diesel = "0.5.0"
router = "0.1.0"
serde = "0.6.11"
serde_json = "0.6.0"
serde_macros = "0.6.11"
staticfile = "0.1.0"
time = "0.1.34"

[dependencies.bodyparser]
git = "https://github.com/iron/body-parser.git"

[dependencies.diesel_codegen]
default-features = false
features = ["nightly", "postgres"]
version = "0.5.0"
