[package]
authors = ["itang <live.tang@gmail.com>"]
name = "deftype-server-rs"
version = "0.1.0"

[dependencies]
ansi_term = "0.7.1"
chrono = "0.2.19"
clippy = "0.0.37"
hyper = "0.7.2"
iron = "0.2.6"
lazy_static = "0.1.15"
mount = "0.0.9"
router = "0.1.0"
rustc-serialize = "0.3.16"
staticfile = "0.1.0"
time = "0.1.34"

diesel = "0.5.0"
diesel_codegen = { version = "0.5.0", default-features = false, features = ["postgres"] }
dotenv = "0.8.0"
dotenv_macros = { version = "0.8.0", optional = true }

[build-dependencies]
syntex = { version = "0.26.0", optional = true }
diesel_codegen = { version = "0.5.0", default-features = false, features = ["postgres"] }
dotenv_codegen = { version = "0.8.0",  optional = true }

[features]
default = ["nightly"]
with-syntex = ["syntex", "diesel_codegen/with-syntex", "dotenv_codegen"]
nightly = ["diesel/unstable", "diesel_codegen/nightly", "dotenv_macros"]
