[package]
authors = ["itang <live.tang@gmail.com>"]
name = "deftype-server-rs"
version = "0.1.0"

[dependencies]
ansi_term = "0.7.2"
bcrypt = "0.1.0"
chrono = "0.2.19"
clippy = "*"

# dotenv = "0.8.0"
dotenv = { git = "https://github.com/slapresta/rust-dotenv.git" }
# dotenv_macros = "0.8.0"
dotenv_macros = { git = "https://github.com/slapresta/rust-dotenv.git" }

hyper = "0.7.2"
iron = "0.2.6"
jwt = "0.4.0"
lazy_static = "0.1.15"
mount = "0.0.10"
r2d2 = "0.6.3"
r2d2-diesel = "0.5.0"
router = "0.1.0"
rust-crypto = "0.2.34"
serde = "0.6.13"
serde_json = "0.6.0"
serde_macros = "0.6.13"
staticfile = "0.1.0"
time = "0.1.34"

[dependencies.bodyparser]
git = "https://github.com/iron/body-parser.git"

[dependencies.diesel]
# version = "0.5.0"
git = "https://github.com/sgrif/diesel.git"

[dependencies.diesel_codegen]
default-features = false
features = ["nightly", "postgres"]
# version = "0.5.0"
git = "https://github.com/sgrif/diesel.git"
